// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLa56Yanh9VtwY3y7LItzfN23_PJgocVs',
    appId: '1:959540668858:web:2df8f45d4f3a1ef4619583',
    messagingSenderId: '959540668858',
    projectId: 'gofood-294a4',
    authDomain: 'gofood-294a4.firebaseapp.com',
    storageBucket: 'gofood-294a4.firebasestorage.app',
    measurementId: 'G-V64Y531ZSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFVHC9n4FNjhV5ef91wptu_cpoIPliLck',
    appId: '1:959540668858:android:41600989f56315f5619583',
    messagingSenderId: '959540668858',
    projectId: 'gofood-294a4',
    storageBucket: 'gofood-294a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbZF2bSzLbI5dK8lo9L3oPqDMvX3PbSxU',
    appId: '1:959540668858:ios:44d92284495d82d7619583',
    messagingSenderId: '959540668858',
    projectId: 'gofood-294a4',
    storageBucket: 'gofood-294a4.firebasestorage.app',
    iosBundleId: 'com.example.goFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbZF2bSzLbI5dK8lo9L3oPqDMvX3PbSxU',
    appId: '1:959540668858:ios:44d92284495d82d7619583',
    messagingSenderId: '959540668858',
    projectId: 'gofood-294a4',
    storageBucket: 'gofood-294a4.firebasestorage.app',
    iosBundleId: 'com.example.goFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLa56Yanh9VtwY3y7LItzfN23_PJgocVs',
    appId: '1:959540668858:web:42ab9565addce4a2619583',
    messagingSenderId: '959540668858',
    projectId: 'gofood-294a4',
    authDomain: 'gofood-294a4.firebaseapp.com',
    storageBucket: 'gofood-294a4.firebasestorage.app',
    measurementId: 'G-YK28N48MH3',
  );
}
